### ISSUE TITLE
Prevent error messages from displaying twice

### ISSUE THREAD

**Issue by zoffixznet** [raku-community-modules/Subset-Helper#1]

**Comment by briandfoy** [comment]
I wondered about this in my Stackoverflow question [about where clauses failing with X::AdHoc](http://stackoverflow.com/q/40097868/2766176). I thought I read somewhere that two different things check the `where`, but I can't find that again.

**Comment by zoffixznet** [comment]
I think the second time is called during error generation. Below, if you change the subset to return 1 at the end, the print out happens only once. You can probably find the location in code by adjusting the number given to callframe in this code:

```
zoffix@leliana:~/CPANPRC/rakudo$ ./perl6 -e 'subset Foo where { dd [ .file, .line given callframe 1 ]; 0}; sub (Foo $) {}(1)'
["gen/moar/m-CORE.setting", "7981"]
["gen/moar/m-CORE.setting", "7981"]
Constraint type check failed for parameter '<anon>'
  in sub  at -e line 1
  in block <unit> at -e line 1

zoffix@leliana:~/CPANPRC/rakudo$ ./perl6 -e 'subset Foo where { dd [ .file, .line given callframe 2 ]; 0}; sub (Foo $) {}(1)'
["gen/moar/m-Metamodel.nqp", "3472"]
["gen/moar/m-Metamodel.nqp", "3472"]
Constraint type check failed for parameter '<anon>'
  in sub  at -e line 1
  in block <unit> at -e line 1

zoffix@leliana:~/CPANPRC/rakudo$ 
```

**Comment by zoffixznet** [comment]
Just change `note` to `fail`. We're going to crash and burn anyway, so why `note` it.
